/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Farshad' at '6/28/17 2:11 PM' with Gradle 2.14.1
 *
 * @author Farshad, @date 6/28/17 2:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
